### ISSUE TITLE
Ἀθήναιος instead of Ἀθηναῖος

### ISSUE THREAD

**Issue by gregorycrane** [perseids-publications/gorman-trees#5]
Ἀθήναιος seems to have slipped in where we should have Ἀθηναῖος in a number of passages. I don't think we get him in Thuc. That name may be valid elsewhere but I think that the default assumption should probably remain the adjective Ἀθηναῖος

**Comment by zfletch** [comment]
Thanks for reporting this issue. Vanessa is actively working on it and the treebanks should be fixed in the next round of updates.
