### ISSUE TITLE
processing Morpheus output

### ISSUE THREAD

**Issue by gregorycrane** [perseids-publications/gorman-trees#7]
It might be worth thinking about how best to extract default postag data from Morpheus output. A student of mine found that the postag for δεῖ labelled this as being imperfect (rather than present). The error may come from the Morpheus output.

I checked.

The raw Morpheus output for δεῖ includes:

imperf ind act 3rd sg	attic epic	contr unaugmented	evw_pr,e_stem

This may have made it into Perseids -- that attic tag is promising. the unaugmented tag would disqualify this from Greek prose.

I am not sure how much work it is worth improving raw Morpheus output but a few hacks might help a fair amount.

Perseus-2:grcwork gcrane2$ cruncher
dei=
dei=
<NL>V de/w1  pres ind act 3rd sg	attic epic doric ionic	contr	evw_pr,e_stem</NL><NL>V de/w1  pres ind mp 2nd sg	attic epic doric ionic	contr	evw_pr,e_stem</NL><NL>V de/w1  imperf ind act 3rd sg	attic epic	contr unaugmented	evw_pr,e_stem</NL><NL>V de/w1  pres imperat act 2nd sg	attic epic	contr	evw_pr,e_stem</NL><NL>V de/w2  pres ind act 3rd sg	attic epic doric ionic	contr	evw_pr,ev_stem</NL><NL>V de/w2  pres ind mp 2nd sg	attic epic doric ionic	contr	evw_pr,ev_stem</NL><NL>V de/w2  pres imperat act 2nd sg	attic epic	contr	evw_pr,ev_stem</NL><NL>V de/w2  imperf ind act 3rd sg	attic epic	contr unaugmented	evw_pr,ev_stem</NL><NL>V dei=  imperf ind act 3rd sg	attic epic	contr unaugmented	ew_pr,ev_stem</NL><NL>V dei=  pres ind act 3rd sg	attic epic doric ionic	contr	ew_pr,ev_stem</NL>

**Comment by zfletch** [comment]
Thanks for pointing out the issue with (δεῖ) and thank you to your student who was looking through the treebanks so carefully! That particular issue should be fixed for this set of treebanks ([commit](https://github.com/perseids-publications/gorman-trees/commit/fa7d4679fbb475962e18fd162f1b3ca681896df0)).

---

I agree that the Arethusa editor should give users suggested forms that make sense. Although I think that the less likely forms should probably still appear. For example, they would be used if an Attic author quotes Homer. Ordering the results and putting the "standard" Attic ones first may help. 

There are three places where something like this can be done:

1. the Morpheus code itself
2. the Morpheus API
3. the Arethusa front end 

There is some ordering done by the Arethusa front end (3) already. The [morph_local_storage](https://github.com/alpheios-project/arethusa/blob/efc131d09b7405915034d2be092aa3d7edb6b063/app/js/arethusa.morph/services/morph_local_storage.js) module stores the forms that a user clicks on and places the more commonly used forms before the less commonly used forms.

I think future changes should focus on the Morpheus API (2). That would allow any application using the API, and not just Arethusa, to benefit. It would also probably be easier than making changes to the Morpheus codebase.

I've done some work on the API. Making it faster and easier to work with is in our long term plan. Though I'm not sure when I'll be able to dedicate time to it. 

For now I'll keep this issue open to collect suggestions about how best to sort/filter the output of Morpheus.

**Comment by zfletch** [comment]
The Morpheus Perseids API is now in good shape to start working on this. I'm closing the issue here in favor of https://github.com/perseids-tools/morpheus-perseids-api/issues/12
