### ISSUE TITLE
In the postag, when is ἀλλά an adverb and when is it a conjunction?

### ISSUE THREAD

**Issue by chrisdrymon** [perseids-publications/gorman-trees#8]
The AGDT 2.0 Guidelines don't seem to clarify the annotations I'm seeing with ἀλλά. When it is an adverb and when is it a conjunction?

**Comment by vgorman1** [comment]
Usually it is an ADV when it is acting as an AuxY at the beginning of a sentence, and it is a COORD when it is conjoining two clauses within the sentence.  Often ἀλλά is the coordinator at the highest level, joining two independent clauses (PRED_CO) and hanging off the root.

Vanessa B. Gorman
Professor of Ancient History
Department of History
619 Oldfather Hall
University of Nebraska-Lincoln
Lincoln, NE 68588-0327
https://vgorman1.github.io/

**Comment by chrisdrymon** [comment]
Excellent, thank you very much! And thank you for your work, Dr. Gorman!
